spring.application.name=my-todo-list

driver_class_name=${DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
db_user=${DB_USER:octotask}
dbpassword=${DB_PASSWORD:Juanddios_1234}
db_url=${DB_URL:jdbc:oracle:thin:@mgqba7appqlizl1d_tp?TNS_ADMIN=./wallet/Wallet_MGQBA7APPQLIZL1D}

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=INFO